/* SPDX-License-Identifier: GPL-3.0-or-later */
/**
 * @file bm_schedule_map_reg.h
 * @brief Schedule-map register-unit contract: CMake-generated or hand-written,
 * see spec section 2.2 (compile-time schedule-map export)
 *
 * @details A "register unit" is a small translation unit (generated by
 * `bm_add_schedule_map()` in CMake, or hand-written for IDE tier-2/3 use)
 * that lists the real `bm_tt_schedule_t` tables an application wants
 * exported, plus optional reference-clock/operating-point metadata for the
 * JSON export (see `bm_tt_schedule_json_meta_t`). The generic dump program
 * `bm_schedule_map_main.c` links against exactly one register unit and
 * iterates `g_bm_schedule_map_entries[]` to produce `.txt`/`.json` per table.
 *
 * @author zeh (china_qzh@163.com)
 * @version 1.0
 * @date 2026-07-03
 *
 * @par Change log:
 *
 *    Date         Version        Author          Description
 * 2026-07-03       1.0            zeh            Task 3: initial register-unit contract
 *
 */
#ifndef BM_SCHEDULE_MAP_REG_H
#define BM_SCHEDULE_MAP_REG_H

#include "bm_tt_schedule.h"

/** @brief One schedule table entry: table instance + owning CPU */
typedef struct {
    bm_tt_schedule_t *sched; /**< Table instance (extern-referenced from the application's assembly unit) */
    uint8_t            cpu;   /**< CPU that owns this table */
} bm_schedule_map_entry_t;

/** @brief Table entries this register unit exports (array, size = g_bm_schedule_map_entry_count) */
extern const bm_schedule_map_entry_t g_bm_schedule_map_entries[];
/** @brief Number of entries in g_bm_schedule_map_entries[] */
extern const uint32_t g_bm_schedule_map_entry_count;
/** @brief wcet reference clock in Hz shared by all tables in this register unit; 0 = undeclared */
extern const uint32_t g_bm_schedule_map_ref_clk_hz;
/** @brief Operating-point frequency array (>=1 placeholder element even when count is 0) */
extern const uint32_t g_bm_schedule_map_op_points_hz[];
/** @brief Real element count of g_bm_schedule_map_op_points_hz[] (may be 0) */
extern const uint32_t g_bm_schedule_map_op_point_count;

/**
 * @brief Register-unit setup hook: open buses / prepare whatever the
 * assembled tables need before bm_tt_schedule_init() is called
 *
 * @return 0 on success; non-zero aborts the dump with an error
 */
int bm_schedule_map_setup(void);

#endif /* BM_SCHEDULE_MAP_REG_H */
