# 将 CMake BM_ENABLE_* 同步为编译期 BM_CONFIG_ENABLE_*（与 bm_config.h 默认值可被 -D 覆盖）

function(bm_export_config_enable target)
    target_compile_definitions(${target} INTERFACE
        BM_CONFIG_ENABLE_MODULE=$<BOOL:${BM_ENABLE_MODULE}>
        BM_CONFIG_ENABLE_SHELL=$<BOOL:${BM_ENABLE_SHELL}>
        BM_CONFIG_ENABLE_WDG=$<BOOL:${BM_ENABLE_WDG}>
        BM_CONFIG_ENABLE_HRT=$<BOOL:${BM_ENABLE_HRT}>
        BM_CONFIG_ENABLE_TICKER=$<BOOL:${BM_ENABLE_TICKER}>
        BM_CONFIG_ENABLE_EXEC=$<BOOL:${BM_ENABLE_EXEC}>
        BM_CONFIG_ENABLE_SYNC=$<BOOL:${BM_ENABLE_SYNC}>
        BM_CONFIG_ENABLE_STREAM=$<BOOL:${BM_ENABLE_STREAM}>
        BM_CONFIG_ENABLE_PIPELINE=$<BOOL:${BM_ENABLE_PIPELINE}>
        BM_CONFIG_ENABLE_ALGORITHM=$<BOOL:${BM_ENABLE_ALGORITHM}>
        BM_CONFIG_ENABLE_TT_SCHED=$<BOOL:${BM_ENABLE_TT_SCHEDULE}>
        BM_CONFIG_ENABLE_WCET_MON=$<BOOL:${BM_ENABLE_WCET_MON}>
        BM_CONFIG_ENABLE_BUS=$<BOOL:${BM_ENABLE_BUS}>
        BM_CONFIG_ENABLE_PARAM=$<BOOL:${BM_ENABLE_PARAM}>
        BM_CONFIG_ENABLE_COMPONENT_MOTOR=$<BOOL:${BM_ENABLE_COMPONENT_MOTOR}>
        BM_CONFIG_ENABLE_COMPONENT_BMS=$<BOOL:${BM_ENABLE_COMPONENT_BMS}>
        BM_CONFIG_ENABLE_COMPONENT_POWER=$<BOOL:${BM_ENABLE_COMPONENT_POWER}>
        BM_CONFIG_ENABLE_COMPONENT_DIAGNOSTICS=$<BOOL:${BM_ENABLE_COMPONENT_DIAGNOSTICS}>
        BM_CONFIG_ENABLE_COMPONENT_STREAM=$<BOOL:${BM_ENABLE_COMPONENT_STREAM}>
        BM_CONFIG_ENABLE_COMPONENT_FUSION=$<BOOL:${BM_ENABLE_COMPONENT_FUSION}>
        BM_CONFIG_ENABLE_COMPONENT_PROCESS=$<BOOL:${BM_ENABLE_COMPONENT_PROCESS}>
        BM_CONFIG_ENABLE_COMPONENT_CONTROL_LOOP=$<BOOL:${BM_ENABLE_COMPONENT_CONTROL_LOOP}>
        BM_CONFIG_ENABLE_COMPONENT_TINYML=$<BOOL:${BM_ENABLE_COMPONENT_TINYML}>
        BM_CONFIG_ENABLE_EXTENSIONS=$<BOOL:${BM_ENABLE_EXTENSIONS}>
    )
endfunction()
