# BM_BACKEND → arch / vendor / sim / pack 目录解析（向后兼容）

function(bm_port_resolve_backend backend out_arch out_vendor out_sim out_pack_dir)
    set(_arch "")
    set(_vendor "")
    set(_sim "")
    set(_pack "")

    if(backend STREQUAL "sdk_stm32g4")
        set(_arch armv7em)
        set(_vendor stm32g4)
        set(_pack ${BM_FRAMEWORK_ROOT}/portable/packs/sdk_stm32g4)
    elseif(backend STREQUAL "native_sim")
        set(_arch host)
        set(_sim native)
        set(_pack ${BM_FRAMEWORK_ROOT}/portable/packs/native_sim)
    elseif(backend STREQUAL "qemu_cortex_m0")
        set(_arch armv6m)
        set(_sim qemu_cm0)
        set(_pack ${BM_FRAMEWORK_ROOT}/portable/packs/qemu_cortex_m0)
    elseif(backend STREQUAL "register_ch32v003")
        set(_arch riscv32)
        set(_vendor ch32v003)
        set(_pack ${BM_FRAMEWORK_ROOT}/portable/packs/register_ch32v003)
    elseif(backend STREQUAL "qemu_riscv64")
        set(_arch riscv64)
        set(_sim qemu_riscv64)
        set(_pack ${BM_FRAMEWORK_ROOT}/portable/packs/qemu_riscv64)
    elseif(backend STREQUAL "sdk_esp32_idf")
        set(_arch xtensa)
        set(_vendor esp32_idf)
        set(_pack ${BM_FRAMEWORK_ROOT}/portable/packs/sdk_esp32_idf)
    elseif(backend STREQUAL "arch_stub")
        set(_arch stub)
        set(_pack ${BM_FRAMEWORK_ROOT}/portable/packs/arch_stub)
    endif()

    set(${out_arch} ${_arch} PARENT_SCOPE)
    set(${out_vendor} ${_vendor} PARENT_SCOPE)
    set(${out_sim} ${_sim} PARENT_SCOPE)
    set(${out_pack_dir} ${_pack} PARENT_SCOPE)
endfunction()

function(bm_port_apply_backend backend hal_target)
    if(backend STREQUAL "external")
        return()
    endif()

    bm_port_resolve_backend(${backend} _arch _vendor _sim _pack)

    if(_pack AND EXISTS "${_pack}/CMakeLists.txt")
        add_subdirectory(${_pack} _bm_pack_${backend})
        return()
    endif()

    # 旧路径回退（仅 Phase 3 前仍驻留 portable/ 的后端，如 sdk_esp32_idf）
    if(EXISTS "${BM_FRAMEWORK_ROOT}/portable/${backend}/CMakeLists.txt")
        add_subdirectory(${BM_FRAMEWORK_ROOT}/portable/${backend}
            _bm_legacy_${backend})
        return()
    endif()

    message(FATAL_ERROR "Unknown BM_BACKEND '${backend}' (no pack or legacy dir)")
endfunction()
