set(CMAKE_SYSTEM_NAME Generic)
set(CMAKE_SYSTEM_PROCESSOR xtensa)
set(CMAKE_TRY_COMPILE_TARGET_TYPE STATIC_LIBRARY)
list(APPEND CMAKE_TRY_COMPILE_PLATFORM_VARIABLES ZEPHYR_SDK_INSTALL_DIR)

if(WIN32 OR MINGW OR CMAKE_HOST_WIN32)
    set(_BM_HOST_EXE ".exe")
else()
    set(_BM_HOST_EXE "")
endif()

if(DEFINED ZEPHYR_SDK_INSTALL_DIR)
    set(_BM_ZEPHYR_SDK_ROOT "${ZEPHYR_SDK_INSTALL_DIR}")
elseif(DEFINED ENV{ZEPHYR_SDK_INSTALL_DIR})
    set(_BM_ZEPHYR_SDK_ROOT "$ENV{ZEPHYR_SDK_INSTALL_DIR}")
endif()

if(DEFINED _BM_ZEPHYR_SDK_ROOT)
    # Zephyr SDK 旧布局：$ZEPHYR_SDK_INSTALL_DIR/<triplet>/bin/
    set(_BM_ZEPHYR_TOOLCHAIN_PREFIX "${_BM_ZEPHYR_SDK_ROOT}/xtensa-espressif_esp32_zephyr-elf/bin")
    # Zephyr SDK ≥ 0.16 新布局：$_BM_ZEPHYR_SDK_ROOT/gnu/<triplet>/bin/
    if(NOT EXISTS "${_BM_ZEPHYR_TOOLCHAIN_PREFIX}/xtensa-espressif_esp32_zephyr-elf-gcc${_BM_HOST_EXE}")
        set(_BM_ZEPHYR_TOOLCHAIN_PREFIX "${_BM_ZEPHYR_SDK_ROOT}/gnu/xtensa-espressif_esp32_zephyr-elf/bin")
    endif()
    if(EXISTS "${_BM_ZEPHYR_TOOLCHAIN_PREFIX}/xtensa-espressif_esp32_zephyr-elf-gcc${_BM_HOST_EXE}")
        set(_pfx "${_BM_ZEPHYR_TOOLCHAIN_PREFIX}/xtensa-espressif_esp32_zephyr-elf")
        set(CMAKE_C_COMPILER   "${_pfx}-gcc${_BM_HOST_EXE}")
        set(CMAKE_ASM_COMPILER "${_pfx}-gcc${_BM_HOST_EXE}")
        set(CMAKE_OBJCOPY      "${_pfx}-objcopy${_BM_HOST_EXE}")
        set(CMAKE_SIZE         "${_pfx}-size${_BM_HOST_EXE}")
    endif()
endif()

if(DEFINED ENV{IDF_PATH})
    set(_BM_ESP32_TOOLCHAIN_PREFIX "$ENV{IDF_PATH}/tools/xtensa-esp-elf/xtensa-esp-elf/bin")
    if(EXISTS "${_BM_ESP32_TOOLCHAIN_PREFIX}/xtensa-esp32-elf-gcc")
        set(CMAKE_C_COMPILER "${_BM_ESP32_TOOLCHAIN_PREFIX}/xtensa-esp32-elf-gcc")
        set(CMAKE_ASM_COMPILER "${_BM_ESP32_TOOLCHAIN_PREFIX}/xtensa-esp32-elf-gcc")
        set(CMAKE_OBJCOPY "${_BM_ESP32_TOOLCHAIN_PREFIX}/xtensa-esp32-elf-objcopy")
        set(CMAKE_SIZE "${_BM_ESP32_TOOLCHAIN_PREFIX}/xtensa-esp32-elf-size")
    endif()
endif()

if(NOT CMAKE_C_COMPILER)
    set(CMAKE_C_COMPILER xtensa-esp32-elf-gcc)
    set(CMAKE_ASM_COMPILER xtensa-esp32-elf-gcc)
    set(CMAKE_OBJCOPY xtensa-esp32-elf-objcopy)
    set(CMAKE_SIZE xtensa-esp32-elf-size)
endif()

set(CMAKE_C_FLAGS "-mlongcalls -Os -ffunction-sections -fdata-sections -Wall -Wextra -std=c99")
set(CMAKE_EXE_LINKER_FLAGS "-nostdlib -Wl,--gc-sections")
